### ISSUE TITLE
Connect from Internet???

### ISSUE THREAD

**Issue by Trepanator56** [kalsan/proxmox-client#1]
Hi, the script works great on local network. Would there be a way to adapt it to connect from the internet ???

Thanks in advance,

**Comment by kalsan** [comment]
Hi, the internet is just another network, sso proxmox-client does not care about where the access is coming from. If this doesn't work over the Internet, it means that the IP you're entering is a local address and your box is probably sitting behind a NAT. There are two ways to get around that:

- Dangerous: Set up your router such that your Proxmox Box is exposed on the Internet and use the public IP by using a port forwarding. This is a bad idea because it exposes your Proxmox Box out in the wild.
- Better: Set up a VPN into your NAT, connect to it and use proxmox-client from within the VPN.
